---
global:
  scrape_interval: 15s
  evaluation_interval: 15s 
alerting:
  alertmanagers:
    -
      static_configs:
        -
          targets:
            - 0.0.0.0:9093
rule_files:
  - generic-rules.yml
  - collator-rules.yml
scrape_configs:
  -
    job_name: calamari full node
    static_configs:
      -
        targets:
          - fritti.calamari.systems
          - pasta.calamari.systems
          - smoothie.calamari.systems
  -
    job_name: calamari full node (ssl)
    scheme: https
    static_configs:
      -
        targets:
          - calamari.metrics.frootmig.thgttg.com
          - kusama.metrics.frootmig.thgttg.com
          - calamari.metrics.effrafax.pelagos.systems
          - kusama.metrics.effrafax.pelagos.systems
          - relay.metrics.avocado.calamari.systems
          - para.metrics.avocado.calamari.systems
          - relay.metrics.chilli.calamari.systems
          - para.metrics.chilli.calamari.systems
          - relay.metrics.jalapeno.calamari.systems
          - para.metrics.jalapeno.calamari.systems
          - relay.metrics.serrano.calamari.systems
          - para.metrics.serrano.calamari.systems
          - relay.metrics.terumbu.calamari.systems
          - para.metrics.terumbu.calamari.systems
          - relay.metrics.kebab.calamari.systems
          - para.metrics.kebab.calamari.systems
          - relay.metrics.tempura.calamari.systems
          - para.metrics.tempura.calamari.systems
          - relay.metrics.salad.calamari.systems
          - para.metrics.salad.calamari.systems
          - relay.metrics.falafel.calamari.systems
          - para.metrics.falafel.calamari.systems
          - relay.metrics.bokkeum.calamari.systems
          - para.metrics.bokkeum.calamari.systems
  -
    job_name: manta invulnerable collator (ssl)
    scheme: https
    static_configs:
      -
        targets:
          - relay.metrics.alfredi.manta.systems
          - para.metrics.alfredi.manta.systems
          - relay.metrics.birostris.manta.systems
          - para.metrics.birostris.manta.systems
          - relay.metrics.hypostoma.manta.systems
          - para.metrics.hypostoma.manta.systems
          - relay.metrics.japanica.manta.systems
          - para.metrics.japanica.manta.systems
  -
    job_name: manta full node (ssl)
    scheme: https
    static_configs:
      -
        targets:
          - relay.metrics.munkiana.manta.systems
          - para.metrics.munkiana.manta.systems
          - relay.metrics.rochebrunei.manta.systems
          - para.metrics.rochebrunei.manta.systems
          - relay.metrics.pectinata.manta.systems
          - para.metrics.pectinata.manta.systems
          - relay.metrics.thurstoni.manta.systems
          - para.metrics.thurstoni.manta.systems
          - relay.metrics.melanyae.manta.systems
          - para.metrics.melanyae.manta.systems
          - relay.metrics.kuhlii.manta.systems
          - para.metrics.kuhlii.manta.systems
  -
    job_name: dolphin invulnerable validator (ssl)
    scheme: https
    static_configs:
      -
        targets:
          - relay.metrics.eddie.dolphin.red
          - relay.metrics.kwaltz.dolphin.red
          - relay.metrics.prosser.dolphin.red
          - relay.metrics.roosta.dolphin.red
          - relay.metrics.zaphod.dolphin.red
  -
    job_name: dolphin full node (ssl)
    scheme: https
    static_configs:
      -
        targets:
          - relay.metrics.ford.dolphin.red
          - relay.metrics.anjie.dolphin.red
          - relay.metrics.trillian.dolphin.red
  -
    job_name: calamari invulnerable collator (ssl)
    scheme: https
    static_configs:
      -
        targets:
          - relay.metrics.crispy.calamari.systems
          - para.metrics.crispy.calamari.systems
          - relay.metrics.crunchy.calamari.systems
          - para.metrics.crunchy.calamari.systems
          - relay.metrics.hotdog.calamari.systems
          - para.metrics.hotdog.calamari.systems
          - relay.metrics.tasty.calamari.systems
          - para.metrics.tasty.calamari.systems
          - relay.metrics.tender.calamari.systems
          - para.metrics.tender.calamari.systems
  -
    job_name: calamari community collator (ssl)
    scheme: https
    static_configs:
      -
        targets:
          # discord, username: grenade#4222, account id: 810037839433433109
          - calamari.metrics.novgorodian.thgttg.com
          - kusama.metrics.novgorodian.thgttg.com
  -
    job_name: calamari community collator
    static_configs:
      -
        targets:
          # discord, username: hahaschool#0933, account id: 345472606562025472
          - 65.108.122.7:9615
          - 65.108.122.7:9616
  -
    job_name: calamari experimental community collator
    static_configs:
      -
        targets:

          # discord, username: 'shez | staking4all#2774', account id: 556857416243871769
          - calamari.staking4all.org:9615
          - calamari.staking4all.org:9616

          # discord, username: Louis-Klever#6454, account id: 874680910035976272
          - 155.138.138.183:9615
          - 155.138.138.183:9616

          # discord, username: SunshineAutosNodes#8147, account id: 442022506098982962
          - 51.195.63.206:9615
          - 51.195.63.206:9615

          # discord, username: displaystyle#3141, account id: 853952148450312192
          - 146.59.68.182:9615
          - 146.59.68.182:9616
  -
    job_name: calamari experimental community collator (ssl)
    scheme: https
    static_configs:
      -
        targets:
        
          # discord, username: 'Skynode | Let's Node#5805', account id: 428875477252440074
          - calamari.metrics.letsnode.io
          - kusama.metrics.letsnode.io
          
          # discord, username: 'marjashka1309200#3402', account id: 829816003545792513
          - calamari.metrics.favoursanywhere.com
          - kusama.metrics.favoursanywhere.com

          # discord, username: 'Lilia#3086', account id: 398172437826633728
          - calamari.metrics.fundmybirthday.com
          - kusama.metrics.fundmybirthday.com

          # discord, username: 'ioannis | DVN#3081', account id: 817020448369541191
          - calamari.metrics.dp.stakebaby.com
          - kusama.metrics.dp.stakebaby.com

          # discord, username: paddyson#5479, account id: 394870302691295234
          - calamari.pathrocknetwork.org
          - kusama.pathrocknetwork.org

          # telegram, username: actlee, name: 'Pithecus 구르쿠스'
          - calamari.pithecus.co.uk
          - kusama.pithecus.co.uk

          # discord, username: @KyleYoon#3912, account id: 884985330032336936
          - calamari.metrics.substake.app
          - kusama.metrics.substake.app

          # discord, username: @rheeunion#0605, account id: 750371346290180166
          - calamari.rhee.substake.app
          - kusama.rhee.substake.app

          # discord, username: @Rok#1767, account id: 433739418793410562
          - calamari.metrics.calamari.anonstake.com
          - kusama.metrics.calamari.anonstake.com

          # discord, username: @CHARGE#0969, account id: 391754967867981851
          - stats.calamari.themilkywaygang.com
          - stats.kasuma.themilkywaygang.com

          # discord, username: @CHARGE#0969, account id: 391754967867981851
          - stats.calamari.migusha.com
          - stats.kasuma.migusha.com

          # discord, username: Ilhan#8421, account id: 489061151628460032
          - calamari.metrics.staker.space
          - kusama.metrics.staker.space

          # discord, username: pmensik#3434, account id: 482230698367909891
          - calamari.metrics.polkadotters.com
          - kusama.metrics.polkadotters.com

          # discord, username: 'worc0260#7958', account id: 950367739405545532
          - calamari.metrics.cj.kmapro.de
          - kusama.metrics.cj.kmapro.de

          # discord, username: crypto_new#6160, account id: 372171365307908096
          - calamari.brightlystake.com
          - kusama.brightlystake.com

          # discord, username: nettle#4895, account id: 893046884871049227
          - calamari.metrics.nettle.network
          - kusama.metrics.nettle.network
          
          # discord, username: n1trog3n#5776, account id: 391835510009626624
          - calamari.metrics.calamari.stakecraft.com
          - kusama.metrics.calamari.stakecraft.com
          
          # discord, username: 'Eric Ding#8247', account id: 885551168762290237
          - calamari.metrics.calamari.gostake.io
          - kusama.metrics.calamari.gostake.io

          # discord, username: papadritta#9980, account id: 214964573059547136
          - calamari.metrics.rocke7.net
          - kusama.metrics.rocke7.net
          
          # discord, username: jason2d2#6574, account id: 784542134635724801
          - metrics.calamari.mantanetwork.bitmanna.com
          - metrics.kusama.mantanetwork.bitmanna.com
          
          # discord, username: Solitudinem#2127, account id: 608331572369686624
          - calamari.metrics.cryptech.com.ua
          - kusama.metrics.cryptech.com.ua

  -
    job_name: pelagos subsquids
    static_configs:
      -
        targets:
          # manta-dev EC2 instance named squiddy, hosting subsquid-processor 
          - ec2-44-201-207-60.compute-1.amazonaws.com:4357
